name: Docker Image Push

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build_and_push_image:
    uses: campus-geo/workflows/.github/workflows/docker-build-push.yml@main